DATA:
    ROOT: '/PATH/TO/videos'
    TRAIN_FILE: '/PATH/TO/train_list_videos.txt'
    VAL_FILE: '/PATH/TO/val_list_videos.txt'
    DATASET: something-somethingv2
    NUM_FRAMES: 16
    NUM_CLASSES: 174
    LABEL_LIST: 'labels/something-something-v2-labels.csv'
    INPUT_SIZE: 336
MODEL:
    ARCH: ViT-L/14@336px
TRAIN:
    BATCH_SIZE: 1
    ACCUMULATION_STEPS: 32